version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: amigoscode
    ports:
      - "3307:3306"  # Map MySQL container's port 3306 to host port 3307
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
