version: '3.9'

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: amigoscode
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
volumes:
  mysql_data:
