version: '3.9'

services:
  mysql:
    container_name: mysql
    image: mysql:8.4.2
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: amigoscode
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - spring

  eureka-server:
    image: aymanwael/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin

  apigw:
    image: aymanwael/apigw:latest
    container_name: apigw
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server

  customer:
    image: aymanwael/customer:latest
    container_name: customer
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - mysql
    depends_on:
      - eureka-server
      - zipkin
      - mysql
      - rabbitmq

  fraud:
    image: aymanwael/fraud:latest
    container_name: fraud
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - mysql
    depends_on:
      - eureka-server
      - zipkin
      - mysql
      - rabbitmq

  notification:
    image: aymanwael/notification:latest
    container_name: notification
    ports:
      - "8999:8999"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - mysql
    depends_on:
      - eureka-server
      - zipkin
      - mysql
      - rabbitmq

networks:
  mysql:
    driver: bridge
  spring:
    driver: bridge

volumes:
  mysql_data:
