server:
  port: 8999
spring:
  application:
    name: notification

  datasource:
    url: jdbc:mysql://localhost:3306/notification?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  zipkin:
    base-url: http://localhost:9411
  eureka:
    client:
      fetch-registry: true
      register-with-eureka: true
      application:
        name: notification

  rabbitmq:
    exchanges:
      internal: internal.exchange
    queue:
        notification: notification.queue
    routing-keys:
        internal-notification: internal.notification.routing-key