spring:
  application:
    name: eureka-server

server:
  port: 8761

zipkin:
  base-url: http://zipkin:9411

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

cloud:
  discovery:
    enabled: false
